services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_pass
      POSTGRES_DB: payment_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment_user -d payment_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - ./payment-data:/var/lib/postgresql/data

  nats:
    image: nats:alpine3.22
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--jetstream", "--store_dir", "/data", "--http_port", "8222"]
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "4222"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - ./nats-data:/data

  payment-service:
    build:
      context: .
      dockerfile: ./services/payment/Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_healthy
    environment:
      DB_URL: "postgres://payment_user:payment_pass@db:5432/payment_db?sslmode=disable"
      NATS_URL: "nats://nats:4222"
      GRPC_PORT: "50051"

  notification-service:
    build:
      context: .
      dockerfile: ./services/notification/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_healthy
    environment:
      DB_URL: "postgres://payment_user:payment_pass@db:5432/payment_db?sslmode=disable"
      NATS_URL: "nats://nats:4222"
